### ISSUE TITLE
챕터 8 - 9에서 creature.py(model, fake 디렉토리 내에서)의 aka 기본값 관련 문제

### ISSUE THREAD

**Issue by WoongheeLee** [rumbarum/fastapi-book-example#17]
안녕하세요. 현재 챕터 8까지 읽고 챕터 9 읽는 중인데요. 

model/creature.py에서 Creature 클래스 정의할 때, aka에 기본값을 줘야 하지 않나요? 
기본값 없이 만들어지는 fake/creature.py는 pydantic에서 에러를 뿜어서요.

감사합니다.

**Comment by WoongheeLee** [comment]
책을 보고 따라 치다보니 Yeti의 aka가 위에 있던 걸 못봤네요.

**Comment by rumbarum** [comment]
안녕하세요 @WoongheeLee 님,
금방 답을 찾으셨다니 다행입니다.
이슈 있으시면 언제든지 제보 부탁드립니다.
